name: "order-service"
database:
  type: "postgres"
  setup: true
  connection:
    host: "127.0.0.1"
    database: "order-service"
    user: "postgres"
    password: ""
dev:
  host: "127.0.0.1"
  port: 5000
