apiVersion: v1
kind: Service
metadata:
  name: stock-service-cass-loadbalancer
spec:
  selector:
    app: stock-service-cass
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-cass
spec:
  selector:
    matchLabels:
      app: stock-service-cass
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-service-cass
    spec:
      containers:
      - name: stock-service
        image: stock-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_SETUP
          value: "True"
        - name: DB_HOST
          value: ""
        - name: DB_PASS
          value: "stockservicedev"

